### ISSUE TITLE
New design tracking issue

### ISSUE THREAD

**Issue by vberger** [vberger/wayland-client-rs#60]
List of things still to be done:

**wayland-scanner**:
- [x] Handle enums _(required for v0.7)_
- [x] Handle bitfields _(required for v0.7)_
- [x] Write usage documentation _(required for v0.7)_

**wayland-client**:
- [x] Write remaining dispatch/flush methods _(required for v0.7)_
- [x] Make query of protocol errors possible ( #33 )
- [ ] Write basic utilities for handling global objects automatically

**wayland-server**:
- [x] Write remaining dispatch/flush methods _(required for v0.7)_
- [x] Write global declaration/instantiation interface _(required for v0.7)_
- [ ] Add support for signals and listeners
- [ ] Add support for more than one event loop

**Comment by vberger** [comment]
cc @Timidger I guess you'll want to follow that.

The docs for the new versions are now built by travis on http://vberger.github.io/wayland-client-rs/

**Comment by vberger** [comment]
I *think* most of the big machinery is in place. I'll need to flesh out the docs some more before releasing the 0.7 though.

**Comment by vberger** [comment]
Closing in favor of sub-issues.
